[package]
name = "bad_robot"
description = "Reddit code challenge - Opperheimer"
authors = ["General Zod"]
license = "MIT"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
rand="0.8.4"
